openapi: 3.0.0
info:
    title: Train API
    version: 1.0.0
    description: Train API documentation
servers:
    - url: http://localhost:3000/api

tags:
    - name: Auth
      description: Operations related to user authentication

paths:
    /register:
        post:
            tags:
                - Auth
            summary: User registration
            description: Register a new user in the system
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                    description: Desired username
                                password:
                                    type: string
                                    description: User's password
                                name:
                                    type: string
                                    description: User's full name
                            required:
                                - username
                                - password
                                - name
            responses:
                200:
                    description: Registration successful
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    userId:
                                        type: string
                                        description: The ID of the newly registered user
                                    token:
                                        type: string
                                        description: JWT token for authentication
                                    username:
                                        type: string
                                        description: Registered username
                400:
                    description: Invalid input or missing fields
                409:
                    description: Username already taken
                500:
                    description: Internal server error
    /login:
        post:
            tags:
                - Auth
            summary: User login
            description: Authenticate a user and return a JWT token
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    type: string
                                    description: User's username
                                password:
                                    type: string
                                    description: User's password
                            required:
                                - username
                                - password
            responses:
                200:
                    description: Login successful
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    userId:
                                        type: string
                                    token:
                                        type: string
                                    username:
                                        type: string
                400:
                    description: Invalid username or password
                401:
                    description: Unauthorized
                500:
                    description: Internal server error
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
