openapi: 3.0.0
info:
    title: Train API
    version: 1.0.0
    description: Train API documentation
servers:
    - url: http://localhost:3000/api
paths:
    /{userId}:
        get:
            summary: Fetch user by Id
            description: Retrieve data for a specific user
            security:
                - bearerAuth: []
            parameters:
                - in: path
                  name: userId
                  required: true
                  schema:
                      type: string
                  description: The user ID
            responses:
                200:
                    description: User data retrieved successfully
                401:
                    description: Unauthorized
                404:
                    description: User not found
    /{userId}/profile-data:
        get:
            summary: Fetch user profile data
            description: Retrieve data for a specific user profile
            security:
                - bearerAuth: []
            parameters:
                - in: path
                  name: userId
                  required: true
                  schema:
                      type: string
                  description: The user ID
            responses:
                200:
                    description: User data retrieved successfully
                401:
                    description: Unauthorized
                404:
                    description: User not found
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
